config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'

  root 'recipes#index'

end

app/models/recipe.rb
require 'httparty'

class Recipe

  include HTTParty
  # TODO How does 'key_value'relate to the rest of the code?
  key_value = ENV["FOOD2FORK_KEY"]
  # 'FOOD2FORK_SERVER_AND_PORT' is used by the grader and 
  # needs not be defined. 
  hostport = ENV["FOOD2FORK_SERVER_AND_PORT"] || "www.food2fork.com" 
  base_uri "http://#{hostport}/api"
  # base_uri "http://food2fork.com/api"
  default_params key: ENV["FOOD2FORK_KEY"]
  format :json

  def self.for (keyword)
    get("/search", query: {q: keyword})["recipes"]
  end
end

# http://food2fork.com/api/search?key=2c73eabf0e5d3d8d3dc2b65bea9bf79f&q=chocolate

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  	@search_term = params[:search] || 'chocolate'
  	@recipes = Recipe.for(@search_term)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe Finder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<!-- 
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>
-->

<h2>Searching for: <%= @search_term %></h2>
<p>Powered By Food2Fork.com</p>

<table border="1" cellpadding="5"> 
  <tr class="tableheader">
    <th>Image</th>
    <th>Title</th>
    <th>Social Rank</th>
  </tr>
  <% @recipes.each do |recipe| %>
  <tr class=<%= cycle('even', 'odd') %>>
    <% image_url = recipe["image_url"] %>
    <% recipe_url = recipe["source_url"] %>
    <td class="tablerow">
       <%= link_to( image_tag(image_url, size: "100"), recipe_url ) %>
    </td>  
    <td class="tablerow">
       <%= link_to( (sanitize recipe["title"]), recipe_url ) %>
    </td>
    <td class="tablerow"><%= recipe["social_rank"].round(3) %></td>
  </tr>
  <% end %>
 </table>